apiVersion: v1
kind: Pod

metadata:
  name: pankaj-pod

spec:
  containers:
    - name: veg-container
      image: nginx

      ports:
        - containerPort: 3000

    - name: organic-container
      image: pankajs111/organic-ghee

      ports:
        - containerPort: 5656
